// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fontfamily} from '../models';

export function DeleteFamily(arg1:Array<string>):Promise<void>;

export function GetFonts():Promise<Array<fontfamily.FontFamily>>;

export function InstallFont(arg1:string):Promise<void>;

export function InstallGoogleFont(arg1:string,arg2:string):Promise<void>;
