// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFamily(arg1) {
  return window['go']['main']['App']['DeleteFamily'](arg1);
}

export function GetLocalFontDirectories() {
  return window['go']['main']['App']['GetLocalFontDirectories']();
}

export function GetLocalFonts() {
  return window['go']['main']['App']['GetLocalFonts']();
}

export function InstallGoogleFont(arg1, arg2) {
  return window['go']['main']['App']['InstallGoogleFont'](arg1, arg2);
}

export function InstallLocalFont(arg1, arg2) {
  return window['go']['main']['App']['InstallLocalFont'](arg1, arg2);
}

export function ListArchiveContents(arg1) {
  return window['go']['main']['App']['ListArchiveContents'](arg1);
}
