// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {font} from '../models';

export function DeleteFamily(arg1:Array<string>):Promise<void>;

export function GetLocalFonts():Promise<Array<font.FontFamily>>;

export function InstallGoogleFont(arg1:string,arg2:string):Promise<void>;

export function InstallLocalFont(arg1:string):Promise<void>;

export function RetrieveZipFileNames(arg1:string):Promise<Array<string>>;
