// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteFamily(arg1:models.FontFamily):Promise<void>;

export function GetFonts():Promise<Array<models.FontFamily>>;

export function InstallFont(arg1:string):Promise<void>;
