// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFamily(arg1) {
  return window['go']['main']['App']['DeleteFamily'](arg1);
}

export function GetFonts() {
  return window['go']['main']['App']['GetFonts']();
}

export function InstallFont(arg1) {
  return window['go']['main']['App']['InstallFont'](arg1);
}

export function InstallGoogleFont(arg1, arg2) {
  return window['go']['main']['App']['InstallGoogleFont'](arg1, arg2);
}
